services:
  mysql:
    image: mysql:8.4
    container_name: agenda-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - agenda_mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  agenda_mysql_data:
